"""Init

Revision ID: 00794b756f83
Revises: ae58b345a3f7
Create Date: 2023-05-04 19:52:09.452741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00794b756f83'
down_revision = 'ae58b345a3f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
