"""empty message

Revision ID: 15a6ba1e7b36
Revises: 00794b756f83
Create Date: 2023-05-04 19:57:45.506096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15a6ba1e7b36'
down_revision = '00794b756f83'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
